In [20]:
import numpy as np

In [21]:
A = np.array ([
    [6., -1, -1],
    [1, 1, 10],
    [2, -1, 1]
])

b = np.array ([
    [4],
    [-6],
    [-2],
])

In [22]:
f = A[1, 0] / A[0, 0]
E21 = np.array ([
    [1, 0, 0],
    [-f, 1, 0],
    [0, 0, 1]])

A = E21 @ A
print(A)
E21

[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 2.         -1.          1.        ]]


array([[ 1.        ,  0.        ,  0.        ],
       [-0.16666667,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [23]:
f = A[2, 0] / A[0, 0]
E31 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [-f, 0, 1]])

A = E31 @ A
print(A)
E31

[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 0.         -0.66666667  1.33333333]]


array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [-0.33333333,  0.        ,  1.        ]])

In [24]:
f = A[2, 1] / A[1, 1]
E32 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [0, -f, 1]])

A = E32 @ A
print(np.round(A, 5))
E32

[[ 6.      -1.      -1.     ]
 [ 0.       1.16667 10.16667]
 [ 0.       0.       7.14286]]


array([[1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.57142857, 1.        ]])

In [25]:
R = np.copy(A)
L = np.linalg.inv (E21) @ np.linalg.inv (E31) @ np.linalg.inv (E32)
np.round(L, 5)

array([[ 1.     ,  0.     ,  0.     ],
       [ 0.16667,  1.     ,  0.     ],
       [ 0.33333, -0.57143,  1.     ]])

In [26]:
y = np.linalg.solve (L, b)
y

array([[ 4.        ],
       [-6.66666667],
       [-7.14285714]])

In [27]:
x = np.linalg.solve (R, y)
x

array([[ 1.],
       [ 3.],
       [-1.]])

# Kontrolle

In [28]:
A = np.array ([
    [6., -1, -1],
    [1, 1, 10],
    [2, -1, 1]
])

np.linalg.solve (A, b)

array([[ 1.],
       [ 3.],
       [-1.]])