In [54]:
import numpy as np

In [55]:
A = np.array ([
    [2., -1, 3, 4],
    [1, 0, -2, 7],
    [3, -3, 1, 5],
    [2, 1, 4, 4]
])

b = np.array ([
    [9],
    [11],
    [8],
    [10],
])

In [56]:
f = A[1, 0] / A[0,0]
E21 = np.array ([
    [1, 0, 0, 0],
    [-f, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]])

A = E21 @ A
print(A)
E21

[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 3.  -3.   1.   5. ]
 [ 2.   1.   4.   4. ]]


array([[ 1. ,  0. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [57]:
f = A[2, 0] / A[0,0]
E31 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [-f, 0, 1, 0],
    [0, 0, 0, 1]])

A = E31 @ A
print(A)
E31

[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 0.  -1.5 -3.5 -1. ]
 [ 2.   1.   4.   4. ]]


array([[ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [-1.5,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [58]:
f = A[3, 0] / A[0, 0]
E41 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [-f, 0, 0, 1]])

A = E41 @ A
print(A)
E41

[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 0.  -1.5 -3.5 -1. ]
 [ 0.   2.   1.   0. ]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [-1.,  0.,  0.,  1.]])

In [59]:
f = A[2, 1] / A[1, 1]
E32 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, -f, 1, 0],
    [0, 0, 0, 1]])

A = E32 @ A
print(A)
E32

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    2.    1.    0. ]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 3., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
f = A[3, 1] / A[1, 1]
E42 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, -f, 0, 1]])

A = E42 @ A
print(A)
E42

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.   15.  -20. ]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -4.,  0.,  1.]])

In [61]:
f = A[3, 2] / A[2, 2]
E43 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, -f, 1]])

A = E43 @ A
print(A)
E43

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]


array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.07142857, 1.        ]])

In [62]:
R = np.copy(A)
L = np.linalg.inv (E21) @ np.linalg.inv (E31) @ np.linalg.inv (E32) @ np.linalg.inv (E41) @ np.linalg.inv (E42) @ np.linalg.inv (E43)
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 1.5       , -3.        ,  1.        ,  0.        ],
       [ 1.        ,  4.        , -1.07142857,  1.        ]])

In [63]:
y = np.linalg.solve (L, b)
y

array([[  9. ],
       [  6.5],
       [ 14. ],
       [-10. ]])

In [64]:
x = np.linalg.solve (R, y)
np.round(x, 5)

array([[-1.],
       [ 0.],
       [ 1.],
       [ 2.]])

# Kontrolle

In [65]:
A = np.array ([
    [2., -1, 3, 4],
    [1, 0, -2, 7],
    [3, -3, 1, 5],
    [2, 1, 4, 4]
])

np.round(np.linalg.solve (A, b), 5)

array([[-1.],
       [-0.],
       [ 1.],
       [ 2.]])