In [50]:
import numpy as np

In [51]:
A = np.array ([
    [2, 6, 2],
    [-3, -8, 0],
    [4, 9, 2]])

In [52]:
f = A[1, 0] / A[0, 0]
E21 = np.array ([
    [1, 0, 0],
    [-f, 1, 0],
    [0, 0, 1]])

A = E21 @ A
print(A)
E21

[[2. 6. 2.]
 [0. 1. 3.]
 [4. 9. 2.]]


array([[1. , 0. , 0. ],
       [1.5, 1. , 0. ],
       [0. , 0. , 1. ]])

In [53]:
f = A[2, 0] / A[0, 0]
E31 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [-f, 0, 1]])

A = E31 @ A
print(A)
E31

[[ 2.  6.  2.]
 [ 0.  1.  3.]
 [ 0. -3. -2.]]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-2.,  0.,  1.]])

In [54]:
f = A[2, 1] / A[1, 1]
E32 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [0, -f, 1]])

A = E32 @ A
print(A)
E32

[[2. 6. 2.]
 [0. 1. 3.]
 [0. 0. 7.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 3., 1.]])

In [55]:
L = np.linalg.inv (E21) @ np.linalg.inv (E31) @ np.linalg.inv (E32)

# Kontrolle

In [56]:
A = np.array ([
    [2, 6, 2],
    [-3, -8, 0],
    [4, 9, 2]])
b = np.array ([
    [2],
    [2],
    [3],
])

np.linalg.solve (A, b)

array([[ 2.],
       [-1.],
       [ 2.]])