In [6]:
import numpy as np

In [7]:
A = np.array ([
    [3, -6],
    [-2, 5]])

In [9]:
f = A[1, 0] / A[0, 0]

E21 = np.array ([
    [1, 0],
    [-f, 1]])

A = E21 @ A
A

array([[ 3., -6.],
       [ 0.,  1.]])

In [4]:
R = E21 @ A
L = np.linalg.inv(E21)

L

array([[ 1.        ,  0.        ],
       [-0.66666667,  1.        ]])

# Kontrolle

In [5]:
b = np.array ([
    [0],
    [1]
])

np.linalg.solve (A, b)

array([[2.],
       [1.]])