In [19]:
import numpy as np

In [20]:
A = np.array ([
    [1., 1, 2],
    [-1, -2, 3],
    [3, -7, 4]
])

b = np.array ([
    [8],
    [1],
    [10],
])

In [21]:
f = A[1, 0] / A[0, 0]
E21 = np.array ([
    [1, 0, 0],
    [-f, 1, 0],
    [0, 0, 1]])

A = E21 @ A
print(A)
E21

[[ 1.  1.  2.]
 [ 0. -1.  5.]
 [ 3. -7.  4.]]


array([[1., 0., 0.],
       [1., 1., 0.],
       [0., 0., 1.]])

In [22]:
f = A[2, 0] / A[0, 0]
E31 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [-f, 0, 1]])

A = E31 @ A
print(A)
E31

[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0. -10.  -2.]]


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-3.,  0.,  1.]])

In [23]:
f = A[2, 1] / A[1, 1]
E32 = np.array ([
    [1, 0, 0],
    [0, 1, 0],
    [0, -f, 1]])

A = E32 @ A
print(np.round(A, 5))
E32

[[  1.   1.   2.]
 [  0.  -1.   5.]
 [  0.   0. -52.]]


array([[  1.,   0.,   0.],
       [  0.,   1.,   0.],
       [  0., -10.,   1.]])

In [24]:
R = np.copy(A)
L = np.linalg.inv (E21) @ np.linalg.inv (E31) @ np.linalg.inv (E32)
np.round(L, 5)

array([[ 1.,  0.,  0.],
       [-1.,  1.,  0.],
       [ 3., 10.,  1.]])

In [25]:
y = np.linalg.solve (L, b)
y

array([[   8.],
       [   9.],
       [-104.]])

In [26]:
x = np.linalg.solve (R, y)
x

array([[3.],
       [1.],
       [2.]])

# Kontrolle

In [27]:
A = np.array ([
    [1, 1, 2],
    [-1, -2, 3],
    [3, -7, 4]
])

np.linalg.solve (A, b)

array([[3.],
       [1.],
       [2.]])