In [124]:
import numpy as np

In [125]:
A = np.array ([
    [2, -1, 3, 4],
    [1, 0, -2, 7],
    [3, -3, 1, 5],
    [2, 1, 4, 4]]).astype(float)

In [126]:
f = A[1, 0] / A[0,0]
E21 = np.array ([
    [1, 0, 0, 0],
    [-f, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]])

A = E21 @ A
print(A)
E21

[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 3.  -3.   1.   5. ]
 [ 2.   1.   4.   4. ]]


array([[ 1. ,  0. ,  0. ,  0. ],
       [-0.5,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [127]:
f = A[2, 0] / A[0,0]
E31 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [-f, 0, 1, 0],
    [0, 0, 0, 1]])

A = E31 @ A
print(A)
E31

[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 0.  -1.5 -3.5 -1. ]
 [ 2.   1.   4.   4. ]]


array([[ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [-1.5,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [128]:
f = A[3, 0] / A[0, 0]
E41 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [-f, 0, 0, 1]])

A = E41 @ A
print(A)
E41

[[ 2.  -1.   3.   4. ]
 [ 0.   0.5 -3.5  5. ]
 [ 0.  -1.5 -3.5 -1. ]
 [ 0.   2.   1.   0. ]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [-1.,  0.,  0.,  1.]])

In [129]:
f = A[2, 1] / A[1, 1]
E32 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, -f, 1, 0],
    [0, 0, 0, 1]])

A = E32 @ A
print(A)
E32

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    2.    1.    0. ]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 3., 1., 0.],
       [0., 0., 0., 1.]])

In [130]:
f = A[3, 1] / A[1, 1]
E42 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, -f, 0, 1]])

A = E42 @ A
print(A)
E42

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.   15.  -20. ]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0., -4.,  0.,  1.]])

In [131]:
f = A[3, 2] / A[2, 2]
E43 = np.array ([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, -f, 1]])

A = E43 @ A
print(A)
E43

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]


array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.07142857, 1.        ]])

# Kontrolle

In [134]:
b = np.array ([
    [2],
    [2],
    [3],
])

np.linalg.solve (A, b)

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 3 is different from 4)