In [65]:
import numpy as np

In [66]:
# Define the weights
W1 = np.array([
    [1, 2, 1],
    [1, 2, 2],
]).T

W2 = np.array([
    [1, 2],
    [-2, -4],
    [5, 6],
]).T

W3 = np.array([
    [1],
    [1],
]).T

# Define the biases
B1 = np.array([
    [5],
    [-10],
    [12],
])

B2 = np.array([
    [-100],
    [-200],
])

B3 = np.array([
    [-70],
])

# Define the input
X = np.array([
    [8], 
    [10]
])

In [67]:
# Define activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [68]:
h1 = np.dot(W1, X) + B1
a1 = relu(h1)
a1

array([[23],
       [26],
       [40]])

In [69]:
h2 = np.dot(W2, a1) + B2
a2 = relu(h2)
a2

array([[71],
       [ 0]])

In [72]:
o = np.dot(W3, a2) + B3
y_pred = sigmoid(o)
np.round(y_pred, 2)

array([[0.73]])