In [1]:
import numpy as np

In [2]:
# Define the weights
W1 = np.array([
    [1, 2, 1],
    [1, 2, 2],
]).T

W2 = np.array([
    [1, 2],
    [-2, -4],
    [5, 6],
]).T

W3 = np.array([
    [1, 2],
    [1, 2],
]).T

# Define the biases
B1 = np.array([
    [5],
    [-10],
    [12],
])

B2 = np.array([
    [-100],
    [-200],
])

B3 = np.array([
    [-2],
    [2],
])

# Define the input
X = np.array([
    [8], 
    [10]
])

In [3]:
# Define activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [4]:
h1 = np.dot(W1, X) + B1
a1 = sigmoid(h1)
a1

array([[1.],
       [1.],
       [1.]])

In [5]:
h2 = np.dot(W2, a1) + B2
a2 = sigmoid(h2)
a2

array([[2.03109266e-42],
       [7.55581902e-86]])

In [7]:
o = np.dot(W3, a2) + B3
y_pred = softmax(o)
np.round(y_pred[1], 2)

array([0.98])