In [38]:
import numpy as np

In [39]:
XTilde = np.array([[0, 0],
       [1, 1],
       [1, 2],
       [2, 1],
       [2, 3],
       [3, 2],
       [3, 4],
       [4, 3],
       [4, 4],
       [5, 5]])
XTilde

array([[0, 0],
       [1, 1],
       [1, 2],
       [2, 1],
       [2, 3],
       [3, 2],
       [3, 4],
       [4, 3],
       [4, 4],
       [5, 5]])

In [40]:
m, n = XTilde.shape

In [41]:
M = np.eye (m) - (1 / m) * np.ones ((m, m))
M

array([[ 0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9]])

In [42]:
X = M @ XTilde
X

array([[-2.5, -2.5],
       [-1.5, -1.5],
       [-1.5, -0.5],
       [-0.5, -1.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5,  1.5],
       [ 1.5,  0.5],
       [ 1.5,  1.5],
       [ 2.5,  2.5]])

In [43]:
C = (1 / (m - 1)) * X.T @ X
C

array([[2.5       , 2.16666667],
       [2.16666667, 2.5       ]])

In [44]:
np.linalg.eig(C)

(array([4.66666667, 0.33333333]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))