In [14]:
import numpy as np

In [15]:
# input data as 2D vectors
x1 = np.array([5, 5])
x2 = np.array([1, 2])
x3 = np.array([1, 5])

# weight matrices
Wxh = np.array([1, 2])
Wxq = np.array([1, -1])
Whh = np.array([5])
Wqq = np.array([2])
Why = np.array([5])
Wqy = np.array([3])

# biases
bh = -10
bq = -5
by = -10

# hidden states are initialized with 0
h0 = np.array([0])
q0 = np.array([0])

In [16]:
# Define activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [17]:
h1 = relu(np.dot(Wxh, x1) + np.dot(Whh, h0) + bh)
np.round(h1, 3)

5

In [24]:
q3 = relu(np.dot(Wxq, x3) + np.dot(Wqq, q0) + bq)
np.round(q3, 3)

0

In [25]:
h2 = relu(np.dot(Wxh, x2) + np.dot(Whh, h1) + bh)
np.round(h2, 3)

array([20])

In [26]:
q2 = relu(np.dot(Wxq, x2) + np.dot(Wqq, q3) + bq)
np.round(q2, 3)

array([0])

In [27]:
h3 = relu(np.dot(Wxh, x3) + np.dot(Whh, h2) + bh)
np.round(h3, 3)

101

In [22]:
q1 = relu(np.dot(Wxq, x1) + np.dot(Wqq, q2) + bq)
np.round(q1, 3)

0

In [28]:
y = sigmoid(np.dot(Why, h3) + np.dot(Wqy, q1) + by)
np.round(y, 3)

array([1.])