In [16]:
import numpy as np
import fractions

# np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())}) # display as fractions (1/3)
np.set_printoptions(formatter={'all':lambda x: str(x)}) # display as decimal numbers (0.33333...)

# Lineare Regression

In [3]:
# Datenmatrix X und Vektor y der Zielgrössen

X = np.array([
    [1, -5],
    [1, -4],
    [1, 2],
    [1, 6],
    [1, 7],
])

y = np.array([
    [-2],
    [2],
    [3],
    [5],
    [6],
])

## "X Transformiert * X"

In [7]:
X.T @ X

array([[5, 6],
       [6, 130]])

## Vektor der Regressionskoeffizienten "b-hat"

In [10]:
bhat = np.linalg.inv(X.T @ X) @ X.T @ y
bhat

array([[670/307],
       [158/307]])

## Projektionsmatrix "P"

In [156]:
P = X @ np.linalg.inv(X.T @ X) @ X.T
P

array([[0.8333333333333333, 0.33333333333333326, -0.16666666666666674],
       [0.33333333333333326, 0.33333333333333326, 0.33333333333333326],
       [-0.16666666666666674, 0.33333333333333326, 0.8333333333333333]])

## Residualmatrix "Q"

In [157]:
I = np.identity(P.shape[0])
Q = I - P
Q

array([[0.16666666666666674, -0.33333333333333326, 0.16666666666666674],
       [-0.33333333333333326, 0.6666666666666667, -0.33333333333333326],
       [0.16666666666666674, -0.33333333333333326, 0.16666666666666674]])

## Prädiktionsvektor "y-hat"

In [158]:
yhat = P @ y
yhat

array([[0.6666666666666663],
       [1.6666666666666663],
       [2.666666666666666]])

## Fehlervektor "e"

In [159]:
# entweder
e = y - yhat

# oder
e = Q @ y

e

array([[0.3333333333333337],
       [-0.6666666666666663],
       [0.3333333333333337]])

## SQR

In [160]:
SQR = e.T @ e
SQR

array([[0.6666666666666667]])

## SQT

### Zentrierende Matrix

In [161]:
m, _ = y.shape
M = np.eye (m) - np.ones ((m, m)) / m
print(f"m={m}")
M

m=3


array([[0.6666666666666667, -0.3333333333333333, -0.3333333333333333],
       [-0.3333333333333333, 0.6666666666666667, -0.3333333333333333],
       [-0.3333333333333333, -0.3333333333333333, 0.6666666666666667]])

## SQT ausrechnen

In [162]:
SQT = y.T @ M @ y
SQT

array([[2.666666666666667]])

## Bestimmtheitsmass "R2"

In [163]:
R2 = 1 - SQR/SQT
R2

array([[0.75]])

# Hauptkomponentenanalyse

In [11]:
# Datenmatrix x-tilde
Xtilde = np.array([
    [1, 2],
    [3, -1],
    [5, -2],
    [8, -3],
    [9, -5],
])

## Zentrierende Datenmatrix

In [12]:
m, _ = Xtilde.shape
M = np.eye (m) - np.ones ((m, m)) / m
print(f"m={m}")
M

m=5


array([[4/5, -1/5, -1/5, -1/5, -1/5],
       [-1/5, 4/5, -1/5, -1/5, -1/5],
       [-1/5, -1/5, 4/5, -1/5, -1/5],
       [-1/5, -1/5, -1/5, 4/5, -1/5],
       [-1/5, -1/5, -1/5, -1/5, 4/5]])

## Zentrierte Datenmatrix

In [13]:
X = M @ Xtilde
X

array([[-21/5, 19/5],
       [-11/5, 4/5],
       [-1/5, -1/5],
       [14/5, -6/5],
       [19/5, -16/5]])

## Kovarianzmatrix "C"

In [14]:
C = (1 / (m-1)) * X.T @ X
C

array([[56/5, -83/10],
       [-83/10, 67/10]])

## Eigenwertzerlegung / Spektralzerlegung der Kovarianzmatrix "C"

## Eigenwerte und Eigenvektoren berechnen

In [17]:
ew, ev = np.linalg.eig(C)
print(ew)
print()
print(ev)

[17.54956394243336 0.35043605756663876]

[[0.7942421461138713 0.6076013605452442]
 [-0.6076013605452442 0.7942421461138713]]


### Matrizen zusammensetzen: C = V * A * V.T

- V: Spalten = Eigenvektoren
- A: Diagonalmatrix mit Eigenwerten
- V.T: Zeilen = Eigenvektoren

## Singulärwertzerlegung der zentrierten Datenmatrix X

In [169]:
U, D, VT = np.linalg.svd(X, full_matrices=False)
Sigma = np.diag (D)

print(U)
print()
print(Sigma)
print()
print(VT)

[[-0.6063390625908323 0.6063390625908325]
 [-0.25746437496366703 -0.742535625036333]
 [0.12126781251816647 -0.12126781251816642]
 [0.7425356250363329 0.25746437496366703]]

[[5.787263818288452 0.0]
 [0.0 0.7124447329648512]]

[[0.6154122094026357 0.7882054380161092]
 [-0.7882054380161092 0.6154122094026357]]


# Eigenwerte / Eigenvektoren

In [170]:
A = np.array([
    [3, 7],
    [7, 2],
])

np.linalg.eig(A)

(array([9.517834423809099, -4.5178344238091]),
 array([[0.7318630507095947, -0.681451740775563],
        [0.681451740775563, 0.7318630507095947]]))