In [27]:
import numpy as np

In [28]:
A = np.array([
    [0, 2, 0, 1],
    [2, 2, 3, 2],
    [4, -3, 0, 1],
    [6, 1, -6, 1],
]).astype(float)

b = np.array([
    [0],
    [-2],
    [-7],
    [6],
]).astype(float)

M = np.concatenate((A, b), axis=1)
M

array([[ 0.,  2.,  0.,  1.,  0.],
       [ 2.,  2.,  3.,  2., -2.],
       [ 4., -3.,  0.,  1., -7.],
       [ 6.,  1., -6.,  1.,  6.]])

In [29]:
P = np.array ([
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0],
])

M = P @ M
M

array([[ 6.,  1., -6.,  1.,  6.],
       [ 4., -3.,  0.,  1., -7.],
       [ 2.,  2.,  3.,  2., -2.],
       [ 0.,  2.,  0.,  1.,  0.]])

In [30]:
def gauss_jordan_elimination(M):
    # forward elimination
    for i in range(M.shape[0]):
        # divide row by pivot
        M[i] = M[i] / M[i, i]
        print(M)
        print()
        # subtract row from all other rows
        for j in range(M.shape[0]):
            if j != i:
                M[j] = M[j] - M[i] * M[j, i]
    return M

M = gauss_jordan_elimination(M)
M

[[ 1.          0.16666667 -1.          0.16666667  1.        ]
 [ 4.         -3.          0.          1.         -7.        ]
 [ 2.          2.          3.          2.         -2.        ]
 [ 0.          2.          0.          1.          0.        ]]

[[ 1.          0.16666667 -1.          0.16666667  1.        ]
 [-0.          1.         -1.09090909 -0.09090909  3.        ]
 [ 0.          1.66666667  5.          1.66666667 -4.        ]
 [ 0.          2.          0.          1.          0.        ]]

[[ 1.          0.         -0.81818182  0.18181818  0.5       ]
 [-0.          1.         -1.09090909 -0.09090909  3.        ]
 [ 0.          0.          1.          0.26666667 -1.32      ]
 [ 0.          0.          2.18181818  1.18181818 -6.        ]]

[[ 1.          0.          0.          0.4        -0.58      ]
 [ 0.          1.          0.          0.2         1.56      ]
 [ 0.          0.          1.          0.26666667 -1.32      ]
 [ 0.          0.          0.          1.        

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  1.5       ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  2.6       ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.06666667],
       [ 0.        ,  0.        ,  0.        ,  1.        , -5.2       ]])